backend:
  name: github
  repo: deilsonmartins/gatsby-teste
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "content/assets" # Media files will be stored in the repo under images/uploads
public_folder: "assets" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "ecommerce" # Used in routes, e.g., /admin/collections/blog
    label: "Ecommerce" # Used in the UI
    folder: "content/items" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Id", name: "id", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
